import Category from './Category';
import Brand from './Brand';
import Address from './Address';
import Cart from './Cart';
import Coupon from './Coupon';
import CouponUsages from './CouponUsage';
import CouponUsers from './CouponUser';
import DeliveryCharges from './DeliveryCharge';
import Media from './Media';
import MetaInformation from './MetaInformation';
import ModelHasTag from './ModelHasTag';
import Option from './Option';
import Order from './Order';
import OrderDetailS from './OrderDetail';
import PaymentInfo from './PaymentInfo';
import ProductDetail from './ProductDetail';
import Product from './Product';
import Setting from './Setting';
import Shop from './Shop';
import SocialLink from './SocialLink';
import Stock from './Stock';
import Tag from './Tag';
import Tax from './Tax';
import Variant from './Variant';

const models = {};

models.Category = Category;
models.Brand = Brand;
models.Address = Address;
models.Cart = Cart;
models.Coupon = Coupon;
models.CouponUsage = CouponUsages;
models.CouponUsers = CouponUsers;
models.DeliveryCharges = DeliveryCharges;
models.Media = Media;
models.MetaInformation = MetaInformation;
models.ModelHasTag = ModelHasTag;
models.Option = Option;
models.Order = Order;
models.OrderDetailS = OrderDetailS;
models.Category = Category;
models.PaymentInfo = PaymentInfo;
models.Product = Product;
models.ProductDetail = ProductDetail;
models.Setting = Setting;
models.Shop = Shop;
models.SocialLink = SocialLink;
models.Stock = Stock;
models.Tag = Tag;
models.Tax = Tax;
models.Variant = Variant;

export default models;
